apiVersion: v1
kind: Service
metadata:
  name: dashy
  namespace: homelab
  labels:
    app: dashy
spec:
  selector:
    app: dashy
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
