apiVersion: v1
kind: Service
metadata:
  name: memos
  namespace: homelab
  labels:
    app: memos
spec:
  selector:
    app: memos
  ports:
    - name: http
      protocol: TCP
      port: 5230
      targetPort: 5230
