apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  namespace: homelab
  labels:
    app: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      containers:
        - name: linkding
          image: sissbruecker/linkding:latest
          env:
            - name: LD_DISABLE_BACKGROUND_TASKS
              value: "true"
            - name: LD_DB_ENGINE
              value: "postgres"
            - name: LD_DB_HOST
              value: "postgres"
            - name: LD_DB_PORT
              value: "5432"
            - name: LD_DB_DATABASE
              value: "linkding"
            - name: LD_DB_USER
              valueFrom:
                secretKeyRef:
                  name: linkding-secrets
                  key: LINKDING_DB_USER
            - name: LD_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkding-secrets
                  key: LINKDING_DB_PASSWORD
            - name: LD_SUPERUSER_NAME
              valueFrom:
                secretKeyRef:
                  name: linkding-secrets
                  key: LINKDING_INITIAL_USERNAME
            - name: LD_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkding-secrets
                  key: LINKDING_INITIAL_PASSWORD
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
          readinessProbe:
            exec:
              command: ["curl", "-f", "http://127.0.0.1:9090/health"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
