apiVersion: v1
kind: Service
metadata:
  name: pgweb
  namespace: homelab
  labels:
    app: pgweb
spec:
  selector:
    app: pgweb
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
